version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: terser
    versions:
    - 5.5.1
    - 5.6.0
    - 5.6.1
  - dependency-name: "@11ty/eleventy-img"
    versions:
    - 0.7.8
    - 0.8.0
    - 0.8.2
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.1
    - 7.0.2
  - dependency-name: "@11ty/eleventy-plugin-syntaxhighlight"
    versions:
    - 3.0.6
  - dependency-name: "@11ty/eleventy"
    versions:
    - 0.11.1
